{% set data = load_setup_py_data() %}

package:
  name: "pymt_heatf"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata
    - bmi-fortran=2.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran=2.0

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_heatf
  commands:
    - config_file=$(mmd-stage HeatModelF . > MANIFEST && mmd-query HeatModelF --var=run.config_file.path)
    - bmi-test pymt_heatf.bmi:HeatModelF --config-file=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the heatf BMI.
  home: https://github.com/mdpiper/pymt_heatf
  license: MIT License
  license_file: LICENSE
  dev_url: https://github.com/mdpiper/pymt_heatf
