{% set data = load_setup_py_data() %}

package:
  name: "pymt_heatf"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy 1.11.*
    - model_metadata

  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt_heatf
  commands:  # TODO
    - config_file=$(mmd-stage bmi_heat . > MANIFEST && mmd-query bmi_heat --var=run.config_file.path)
    - bmi-test pymt_heatf.bmi:bmi_heat --infile=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the heatf BMI.
  home: https://github.com/mcflugen/pymt_heatf
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_heatf
