# An env for re/building a Fortran pymt-lab component with Meson.
name: fbld
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - make
  - cmake
  - pkg-config
  - bmi-fortran
  - fortran-compiler
  - c-compiler
  # - cython
  # - meson-python
  - numpy
  - bmi-tester >=0.5.5
  - pymt >=1.3.2
