# A conda environment for re/building a Fortran pymt-lab component with Meson.
name: fbld
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - make
  - cmake  # [bmi-example-fortran]
  - bmi-fortran
  - fortran-compiler
  - c-compiler
  - cxx-compiler  # [win]
  - cython
  - pkg-config
  - meson-python
  - python-build
  - numpy
  - bmi-tester >=0.5.5
  - pymt >=1.3.2
