run_duration:
  description: Simulation run time
  value:
    type: float
    default: 50.0
    units: s
    range:
      min: 0.0
      max: 1000000.0

thermal_diffusivity:
  name: Thermal diffusivity
  description: Thermal diffusivity
  value:
    type: float
    default: 0.75
    range:
      min: 0.0
      max: 10.0
    units: 'm2 s-1'

number_of_rows:
  name: Number of rows
  description: Number of grid rows
  value:
    type: int
    default: 8
    range:
      min: 0
      max: 10000
    units: '-'

number_of_columns:
  name: Number of columns
  description: Number of grid columns
  value:
    type: int
    default: 6
    range:
      min: 0
      max: 10000
    units: '-'
